### ISSUE TITLE
Cannot query childImageSharp field

### ISSUE THREAD

**Issue by Trushar10** [john-smilga/starter-project-gatsby-strapi-portfolio-2020#1]
I am following your tutorial on [YouTube](https://www.youtube.com/watch?v=asB-dUwpH4Y&t=6472s). I am at the chapter of project query where an image will be used for projects. But In graphql, while creating a query there is no field for selecting childImageSharp under image node.

![Screenshot (92)](https://user-images.githubusercontent.com/63665542/119497376-1de6df80-bd82-11eb-91d3-14581e842f8f.png)

**Comment by john-smilga** [comment]
It's under localFile

**Comment by Trushar10** [comment]
> It's under localFile
Thanks.
Why it is in localFile and not Image node?

**Comment by john-smilga** [comment]
Well, that's how they setup in the latest source plugin, and since I did not create the plugin, I'm not sure.
